import { StructuringPipelineOutput } from '../contracts/structuringOutput'
import type { StructuringPipelineOutput as StructuringPipelineOutputType } from '../contracts/structuringOutput'

interface MarkdownLine {
  text: string
  lineNumber: number
}

function simpleHash(value: string): string {
  let hash = 0
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 31 + value.charCodeAt(i)) >>> 0
  }
  return hash.toString(36)
}

function titleFromMarkdown(markdown: string, sourceFile: string): string {
  const heading = markdown
    .split(/\r?\n/)
    .map((line) => line.trim())
    .find((line) => line.startsWith('# '))
  if (heading) return heading.replace(/^#\s+/, '').trim()

  const withoutExtension = sourceFile.replace(/\.[^.]+$/, '').trim()
  return withoutExtension || 'Untitled Markdown Regulation'
}

function reviewableLines(markdown: string): MarkdownLine[] {
  return markdown
    .split(/\r?\n/)
    .map((line, index) => ({ text: line.trim(), lineNumber: index + 1 }))
    .filter((line) => line.text.length > 0)
    .filter((line) => !line.text.startsWith('# '))
}

function classifyLine(text: string): 'chapter' | 'section' | 'article' | 'paragraph' {
  if (/^#{2}\s+/.test(text)) return 'chapter'
  if (/^#{3,}\s+/.test(text)) return 'section'
  if (/^第.+章/.test(text)) return 'chapter'
  if (/^第.+节/.test(text)) return 'section'
  if (/^第.+条/.test(text)) return 'article'
  return 'paragraph'
}

function displayLabel(text: string): string {
  return text.replace(/^#{2,6}\s+/, '').slice(0, 80)
}

export function structureMarkdownForReview(
  markdown: string,
  sourceFile: string = 'markdown-input.md',
  loadedAt: string = new Date().toISOString(),
): StructuringPipelineOutputType {
  const trimmed = markdown.trim()
  if (!trimmed) {
    throw new Error('Markdown input is empty')
  }

  const sourceId = `md-${simpleHash(`${sourceFile}:${trimmed}`)}`
  const documentId = `doc-${sourceId}`
  const title = titleFromMarkdown(markdown, sourceFile)
  const lines = reviewableLines(markdown)
  if (lines.length === 0) {
    throw new Error('Markdown input has no reviewable units')
  }

  let currentChapterId: string | null = null
  let currentSectionId: string | null = null
  const units = lines.map((line, index) => {
    const unitKind = classifyLine(line.text)
    const unitId = `${documentId}-unit-${String(index + 1).padStart(3, '0')}`
    const parentUnitId =
      unitKind === 'chapter'
        ? null
        : unitKind === 'section'
          ? currentChapterId
          : currentSectionId ?? currentChapterId

    if (unitKind === 'chapter') {
      currentChapterId = unitId
      currentSectionId = null
    }
    if (unitKind === 'section') {
      currentSectionId = unitId
    }

    const label = displayLabel(line.text)
    return {
      unit_id: unitId,
      document_id: documentId,
      parent_unit_id: parentUnitId,
      order_index: index,
      unit_level: unitKind === 'chapter' ? 1 : unitKind === 'section' ? 2 : 3,
      unit_kind: unitKind,
      display_label: label,
      source_id: sourceId,
      source_file: sourceFile,
      source_location: {
        kind: 'line_number',
        value: String(line.lineNumber),
        confidence: 1,
      },
      hierarchy: {
        chapter: unitKind === 'chapter' ? label : null,
        section: unitKind === 'section' ? label : null,
        article_number: unitKind === 'article' ? label.match(/^第.+?条/)?.[0] ?? null : null,
        article_title: unitKind === 'article' ? label : null,
        heading_path: [title],
      },
      original_text: line.text,
      normalized_text: displayLabel(line.text),
      semantic_draft: {
        unit_type: 'general',
        normalized_title: label,
        summary: label,
        evidence_text: [line.text],
        confidence: null,
        review_status: 'needs_review',
      },
      review_status: 'needs_review',
      warnings: ['Markdown adapter output requires expert review.'],
    }
  })

  const draft = {
    contract_version: 'v1',
    extraction_provenance: {
      extraction_method: 'deterministic',
      prompt_contract_version: null,
      model_trace_id: null,
    },
    document: {
      document_id: documentId,
      source_id: sourceId,
      source_file: sourceFile,
      classification: {
        source_type: 'internal_policy',
        issuer_type: 'unknown',
        issuer_name: null,
        categories: [],
        topic_tags: [],
        classification_tags: ['markdown_ui_draft'],
        evidence_text: [title],
        confidence: null,
        review_status: 'needs_review',
        ambiguity_notes: ['Generated by UI-local Markdown adapter; expert review required.'],
      },
      title,
      document_number: null,
      document_status: 'unknown',
      effective_date: null,
      promulgation_date: null,
      repeal_date: null,
      temporal_metadata: {
        version_label: null,
        validity_notes: [],
        temporal_confidence: null,
        ambiguity_notes: ['Temporal metadata was not inferred from Markdown input.'],
      },
      parse_status: 'needs_review',
      warnings: [
        `Loaded at ${loadedAt}`,
        'Markdown adapter output is draft-only and not canonical 001 pipeline output.',
      ],
      review_status: 'needs_review',
    },
    units,
    reference_candidates: [],
    dependency_graph: {
      graph_id: `graph-${documentId}`,
      document_id: documentId,
      reference_candidate_ids: [],
      dependency_edges: [],
      warnings: ['No dependency resolution is performed by the Markdown adapter.'],
    },
    validation_report: {
      document_id: documentId,
      summary: 'Markdown input converted to draft review units.',
      findings: [
        {
          stage: 'input',
          target_type: 'pipeline_output',
          target_id: documentId,
          code: 'markdown_ui_draft',
          severity: 'warning',
          message: 'Markdown adapter output requires expert review before downstream use.',
          document_id: documentId,
          unit_id: null,
          source_location: null,
        },
      ],
      error_count: 0,
      warning_count: 1,
      info_count: 0,
      has_errors: false,
    },
  }

  return StructuringPipelineOutput.parse(draft)
}
